name: Run Java Bot Every 6h

on:
  schedule:
    - cron: "0 */6 * * *"   # elke 6 uur
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350    # max runtime (5u50)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Insert Discord token into config
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          sed -i "s/token: 'token hier'/token: '${DISCORD_TOKEN//\//\\/}'/" config.yml
          echo "Discord token injected."

      - name: Run Bot
        run: |
          echo "Starting bot using Java 21..."
          java -Xmx1G -jar chomens_bot-rolling-all.jar
