name: Run ChomeNS Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Inject Discord token into config.yml
        run: |
          sed -i "s|token: 'token hier'|token: '${{ secrets.DISCORD_TOKEN }}'|" config.yml

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Remove Eval section from config.yml
        run: |
          yq eval 'del(.eval)' -i config.yml

      - name: Remove unsupported core fields
        run: |
          sed -i '/^  op:/d' config.yml
          sed -i '/^  gamemode:/d' config.yml
          sed -i '/^  respawn:/d' config.yml

      - name: Start Discord Bot
        run: |
          echo "Starting ChomeNS Discord Bot..."
          java -jar chomens_bot-rolling-all.jar
